//코드
const code = {
  code: [
    {
      _id: "airline",
      title: "항공사 코드",
      codes: [
        {
          code: "KE",
          value: "대한항공",
          nameKor: "대한항공",
          nameEng: "Korean Air",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "OZ",
          value: "아시아나항공",
          nameKor: "아시아나항공",
          nameEng: "Asiana Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "7C",
          value: "제주항공",
          nameKor: "제주항공",
          nameEng: "Jeju Air",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "LJ",
          value: "진에어",
          nameKor: "진에어",
          nameEng: "Jin Air",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "BX",
          value: "에어부산",
          nameKor: "에어부산",
          nameEng: "Air Busan",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "RS",
          value: "에어서울",
          nameKor: "에어서울",
          nameEng: "Air Seoul",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "TW",
          value: "티웨이항공",
          nameKor: "티웨이항공",
          nameEng: "T'way Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "YP",
          value: "에어프레미아",
          nameKor: "에어프레미아",
          nameEng: "Air Premia",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "CA",
          value: "중국국제항공",
          nameKor: "중국국제항공",
          nameEng: "Air China",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "CZ",
          value: "중국남방항공",
          nameKor: "중국남방항공",
          nameEng: "China Southern Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "MU",
          value: "중국동방항공",
          nameKor: "중국동방항공",
          nameEng: "China Eastern Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "HU",
          value: "하이난항공",
          nameKor: "하이난항공",
          nameEng: "Hainan Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "ZH",
          value: "심천항공",
          nameKor: "심천항공",
          nameEng: "Shenzhen Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "MF",
          value: "샤먼항공",
          nameKor: "샤먼항공",
          nameEng: "Xiamen Air",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "3U",
          value: "사천항공",
          nameKor: "사천항공",
          nameEng: "Sichuan Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "SC",
          value: "산동항공",
          nameKor: "산동항공",
          nameEng: "Shandong Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "FM",
          value: "상해항공",
          nameKor: "상해항공",
          nameEng: "Shanghai Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "HO",
          value: "길상항공",
          nameKor: "길상항공",
          nameEng: "Juneyao Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "9C",
          value: "춘추항공",
          nameKor: "춘추항공",
          nameEng: "Spring Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "CX",
          value: "캐세이퍼시픽항공",
          nameKor: "캐세이퍼시픽항공",
          nameEng: "Cathay Pacific Airways",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "HX",
          value: "홍콩항공",
          nameKor: "홍콩항공",
          nameEng: "Hong Kong Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "UO",
          value: "홍콩 익스프레스",
          nameKor: "홍콩 익스프레스",
          nameEng: "HK Express",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "NX",
          value: "에어마카오",
          nameKor: "에어마카오",
          nameEng: "Air Macau",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "CI",
          value: "중화항공",
          nameKor: "중화항공",
          nameEng: "China Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "BR",
          value: "애바항공",
          nameKor: "에바항공",
          nameEng: "EVA Air",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "IT",
          value: "타이거항공 타이완",
          nameKor: "타이거항공 타이완",
          nameEng: "Tigerair Taiwan",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "JX",
          value: "스타럭스항공",
          nameKor: "스타럭스항공",
          nameEng: "STARLUX Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "JL",
          value: "일본항공",
          nameKor: "일본항공",
          nameEng: "Japan Airlines",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "NH",
          value: "전일본공수",
          nameKor: "전일본공수",
          nameEng: "All Nippon Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "GK",
          value: "젯스타 재팬",
          nameKor: "젯스타 재팬",
          nameEng: "Jetstar Japan",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "MM",
          value: "피치항공",
          nameKor: "피치항공",
          nameEng: "Peach Aviation",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "IJ",
          value: "일본춘추항공",
          nameKor: "일본춘추항공",
          nameEng: "Spring Airlines Japan",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "ZG",
          value: "집에어",
          nameKor: "집에어",
          nameEng: "ZIPAIR",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "NQ",
          value: "에어재팬",
          nameKor: "에어재팬",
          nameEng: "Air Japan",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "XM",
          value: "J-에어",
          nameKor: "J-에어",
          nameEng: "J-Air",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "BC",
          value: "스카이마크 항공",
          nameKor: "스카이마크 항공",
          nameEng: "Skymark Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "HD",
          value: "에어 두",
          nameKor: "에어 두",
          nameEng: "Air Do",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "6J",
          value: "솔라시드 항공",
          nameKor: "솔라시드 항공",
          nameEng: "Solaseed Air",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "JH",
          value: "후지드림항공",
          nameKor: "후지드림항공",
          nameEng: "Fuji Dream Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "7G",
          value: "스타플라이어",
          nameKor: "스타플라이어",
          nameEng: "StarFlyer",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "OM",
          value: "미아트 몽골항공",
          nameKor: "미아트 몽골항공",
          nameEng: "MIAT Mongolian Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "M0",
          value: "에어로 몽골리아",
          nameKor: "에어로 몽골리아",
          nameEng: "Aero Mongolia",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "VN",
          value: "베트남항공",
          nameKor: "베트남항공",
          nameEng: "Vietnam Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "VJ",
          value: "비엣젯항공",
          nameKor: "비엣젯항공",
          nameEng: "VietJet Air",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "BL",
          value: "젯스타 퍼시픽 항공",
          nameKor: "젯스타 퍼시픽 항공",
          nameEng: "Jetstar Pacific",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "QH",
          value: "뱀부항공",
          nameKor: "뱀부항공",
          nameEng: "Bamboo Airways",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "QV",
          value: "라오항공",
          nameKor: "라오항공",
          nameEng: "Lao Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "TG",
          value: "타이항공",
          nameKor: "타이항공",
          nameEng: "Thai Airways International",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "FD",
          value: "타이 에어아시아",
          nameKor: "타이 에어아시아",
          nameEng: "Thai AirAsia",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "PG",
          value: "방콕항공",
          nameKor: "방콕항공",
          nameEng: "Bangkok Airways",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "DD",
          value: "녹에어",
          nameKor: "녹에어",
          nameEng: "Nok Air",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "SL",
          value: "타이라이언에어",
          nameKor: "타이라이언에어",
          nameEng: "Thai Lion Air",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "XJ",
          value: "타이 에어아시아 X",
          nameKor: "타이 에어아시아 X",
          nameEng: "Thai AirAsia X",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "8M",
          value: "미얀마 국제항공",
          nameKor: "미얀마 국제항공",
          nameEng: "Myanmar Airways International",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "PR",
          value: "필리핀항공",
          nameKor: "필리핀항공",
          nameEng: "Philippine Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "5J",
          value: "세부퍼시픽",
          nameKor: "세부퍼시픽",
          nameEng: "Cebu Pacific",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "MH",
          value: "말레이시아 항공",
          nameKor: "말레이시아 항공",
          nameEng: "Malaysia Airlines",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "AK",
          value: "에어아시아",
          nameKor: "에어아시아",
          nameEng: "Air Asia",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "OD",
          value: "바틱에어 말레이시아",
          nameKor: "바틱에어 말레이시아",
          nameEng: "Batik Air Malaysia",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "D7",
          value: "에어아시아 X",
          nameKor: "에어아시아 X",
          nameEng: "Air Asia X",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "SQ",
          value: "싱가포르항공",
          nameKor: "싱가포르항공",
          nameEng: "Singapore Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "TR",
          value: "스쿠트항공",
          nameKor: "스쿠트항공",
          nameEng: "Scoot",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "3K",
          value: "젯스타 아시아",
          nameKor: "젯스타 아시아",
          nameEng: "Jetstar Asia Airways",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "GA",
          value: "가루다 인도네시아",
          nameKor: "가루다 인도네시아",
          nameEng: "Garuda Indonesia",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "JT",
          value: "라이온 에어",
          nameKor: "라이온 에어",
          nameEng: "Lion Air",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "AI",
          value: "에어 인디아",
          nameKor: "에어 인디아",
          nameEng: "Air India",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "UL",
          value: "스리랑카 항공",
          nameKor: "스리랑카 항공",
          nameEng: "Srilankan Airlines",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "SV",
          value: "사우디아 항공",
          nameKor: "사우디아 항공",
          nameEng: "Saudia Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "EY",
          value: "에티하드 항공",
          nameKor: "에티하드 항공",
          nameEng: "Etihad Airways",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "EK",
          value: "에미레이트 항공",
          nameKor: "에미레이트 항공",
          nameEng: "Emirates",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "QR",
          value: "카타르 항공",
          nameKor: "카타르 항공",
          nameEng: "Qatar Airways",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "KU",
          value: "쿠웨이트 항공",
          nameKor: "쿠웨이트 항공",
          nameEng: "Kuwait Airways",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "LY",
          value: "엘알",
          nameKor: "엘알",
          nameEng: "El Al",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "ME",
          value: "중동항공",
          nameKor: "중동항공",
          nameEng: "Middle East Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "DL",
          value: "델타항공",
          nameKor: "델타항공",
          nameEng: "Delta Air Lines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "UA",
          value: "유나이티드 항공",
          nameKor: "유나이티드 항공",
          nameEng: "United Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "AA",
          value: "아메리칸 항공",
          nameKor: "아메리칸 항공",
          nameEng: "American Airlines",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "AS",
          value: "알래스카 항공",
          nameKor: "알래스카 항공",
          nameEng: "Alaska Airlines",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "HA",
          value: "하와이안 항공",
          nameKor: "하와이안 항공",
          nameEng: "Hawaiian Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "WN",
          value: "사우스웨스트 항공",
          nameKor: "사우스웨스트 항공",
          nameEng: "Southwest Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "B6",
          value: "젯블루",
          nameKor: "젯블루",
          nameEng: "Jetblue Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "NK",
          value: "스피릿 항공",
          nameKor: "스피릿 항공",
          nameEng: "Spirit Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "F9",
          value: "프론티어 항공",
          nameKor: "프론티어 항공",
          nameEng: "Frontier Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "AC",
          value: "에어 캐나다",
          nameKor: "에어 캐나다",
          nameEng: "Air Canada",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "WS",
          value: "웨스트젯",
          nameKor: "웨스트젯",
          nameEng: "WestJet Airlines",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "AM",
          value: "아에로멕시코",
          nameKor: "아에로멕시코",
          nameEng: "Aero Mexico",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "LA",
          value: "LATAM 칠레 항공",
          nameKor: "LATAM 칠레 항공",
          nameEng: "LATAM Airlines Chile",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "JJ",
          value: "LATAM 브라질 항공",
          nameKor: "LATAM 브라질 항공",
          nameEng: "LATAM Airlines Brazil",
          allianceKor: "",
          allianceEng: "",
          sort: "FSC",
        },
        {
          code: "AR",
          value: "아르헨티나 항공",
          nameKor: "아르헨티나 항공",
          nameEng: "Aerolineas Argentinas",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "LH",
          value: "루프트한자",
          nameKor: "루프트한자",
          nameEng: "Lufthansa",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "BA",
          value: "영국항공",
          nameKor: "영국항공",
          nameEng: "British Airways",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "VS",
          value: "버진 애틀랜틱 항공",
          nameKor: "버진 애틀랜틱 항공",
          nameEng: "Virgin Atlantic Airways",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "U2",
          value: "이지젯",
          nameKor: "이지젯",
          nameEng: "EasyJet",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "BY",
          value: "TUI 에어웨이즈",
          nameKor: "TUI 에어웨이즈",
          nameEng: "TUI Airways",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "EI",
          value: "에어 링구스",
          nameKor: "에어 링구스",
          nameEng: "Aer Lingus",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "FR",
          value: "라이언에어",
          nameKor: "라이언에어",
          nameEng: "RyanAir",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "AF",
          value: "에어프랑스",
          nameKor: "에어프랑스",
          nameEng: "Air France",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "AZ",
          value: "ITA 항공",
          nameKor: "ITA 항공",
          nameEng: "ITA Airways",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "KL",
          value: "KLM 네덜란드 항공",
          nameKor: "KLM 네덜란드 항공",
          nameEng: "KLM Royal Dutch Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "SU",
          value: "아에로플로트",
          nameKor: "아에로플로트",
          nameEng: "Aeroflot",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "S7",
          value: "S7 항공",
          nameKor: "S7 항공",
          nameEng: "S7 Airlines",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "IB",
          value: "이베리아항공",
          nameKor: "이베리아항공",
          nameEng: "Iberia Airlines",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "UX",
          value: "에어 에우로파",
          nameKor: "에어 에우로파",
          nameEng: "Air Europa",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "OK",
          value: "체코항공",
          nameKor: "체코항공",
          nameEng: "Czech Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "RO",
          value: "타롬항공",
          nameKor: "타롬항공",
          nameEng: "TAROM",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "SN",
          value: "브뤼셀 항공",
          nameKor: "브뤼셀 항공",
          nameEng: "Brussels Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "LZ",
          value: "스위스 국제항공",
          nameKor: "스위스 국제항공",
          nameEng: "Swiss International Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "SK",
          value: "스칸디나비아 항공",
          nameKor: "스칸디나비아 항공",
          nameEng: "Scandinavian Airlines",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "OS",
          value: "오스트리아항공",
          nameKor: "오스트리아항공",
          nameEng: "Austrian Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "OU",
          value: "크로아티아항공",
          nameKor: "크로아티아항공",
          nameEng: "Croatia Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "TK",
          value: "터키항공",
          nameKor: "터키항공",
          nameEng: "Turkish Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "LO",
          value: "LOT 폴란드항공",
          nameKor: "LOT 폴란드항공",
          nameEng: "LOT Polish Airlines",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "TP",
          value: "TAP 포르투갈 항공",
          nameKor: "TAP 포르투갈 항공",
          nameEng: "TAP Air Portugal",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "AY",
          value: "핀에어",
          nameKor: "핀에어",
          nameEng: "Finnair",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "QF",
          value: "콴타스",
          nameKor: "콴타스",
          nameEng: "Qantas",
          allianceKor: "원월드",
          allianceEng: "oneworld",
          sort: "FSC",
        },
        {
          code: "JQ",
          value: "젯스타",
          nameKor: "젯스타",
          nameEng: "Jetstar",
          allianceKor: "",
          allianceEng: "",
          sort: "LCC",
        },
        {
          code: "NZ",
          value: "에어 뉴질랜드",
          nameKor: "에어 뉴질랜드",
          nameEng: "Air New Zealand",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "ET",
          value: "에티오피아항공",
          nameKor: "에티오피아항공",
          nameEng: "Ethiopian",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "KQ",
          value: "케냐항공",
          nameKor: "케냐항공",
          nameEng: "Kenya Airways",
          allianceKor: "스카이팀",
          allianceEng: "Skyteam",
          sort: "FSC",
        },
        {
          code: "SA",
          value: "남아프리카항공",
          nameKor: "남아프리카항공",
          nameEng: "South African Airways",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
        {
          code: "MS",
          value: "이집트항공",
          nameKor: "이집트항공",
          nameEng: "Egypt Air",
          allianceKor: "스타얼라이언스",
          allianceEng: "Star Alliance",
          sort: "FSC",
        },
      ],
    },
    {
      _id: "airport",
      title: "공항 코드",
      codes: [
        // `/files/${clientId}/user-muzi.webp`,
        {
          code: "ICN",
          value: "서울/인천",
          nameKor: "인천국제공항",
          nameEng: "Incheon International Airport",
          cityCode: "SEL",
          countryCode: "KR",
          img: `/files/${clientId}/seoul.webp`,
        },
        {
          code: "GMP",
          value: "서울/김포",
          nameKor: "김포국제공항",
          nameEng: "Gimpo International Airport",
          cityCode: "SEL",
          countryCode: "KR",
          img: `/files/${clientId}/seoul.webp`,
        },
        {
          code: "PUS",
          value: "부산/김해",
          nameKor: "김해국제공항",
          nameEng: "Gimhae International Airport",
          cityCode: "PUS",
          countryCode: "KR",
          img: `/files/${clientId}/busan.webp`,
        },
        {
          code: "CJU",
          value: "제주",
          nameKor: "제주국제공항",
          nameEng: "Jeju Internation Airport",
          cityCode: "CJU",
          countryCode: "KR",
          img: `/files/${clientId}/jeju.webp`,
        },
        {
          code: "TAE",
          value: "대구",
          nameKor: "대구국제공항",
          nameEng: "Daegu International Airport",
          cityCode: "TAE",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "CJJ",
          value: "청주",
          nameKor: "청주국제공항",
          nameEng: "Cheongju International Airport",
          cityCode: "CJJ",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "MWX",
          value: "무안",
          nameKor: "무안국제공항",
          nameEng: "Muan International Airport",
          cityCode: "MWX",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "YNY",
          value: "양양",
          nameKor: "양양국제공항",
          nameEng: "Yangyang International Airport",
          cityCode: "YNY",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "USN",
          value: "울산",
          nameKor: "울산공항",
          nameEng: "Ulsan Airport",
          cityCode: "USN",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "RSU",
          value: "여수",
          nameKor: "여수공항",
          nameEng: "Yeosu Airport",
          cityCode: "RSU",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "HIN",
          value: "사천",
          nameKor: "사천공항",
          nameEng: "Sacheon Airport",
          cityCode: "HIN",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "KPO",
          value: "포항",
          nameKor: "포항경주공항",
          nameEng: "Pohang Gyeongju Airport",
          cityCode: "KPO",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
        {
          code: "KUV",
          value: "군산",
          nameKor: "군산공항",
          nameEng: "Gunsan Airport",
          cityCode: "KUV",
          countryCode: "KR",
          img: `/files/${clientId}/korea.webp`,
        },
      ],
    },
    {
      _id: "aircraft",
      title: "항공기 코드",
      codes: [
        {
          code: "333",
          value: "A330-300",
          nameKor: "에어버스 A330-300",
          nameEng: "Airbus A330-300",
          manufacturerKor: "에어버스",
          manufacturerEng: "Airbus",
          specKor: "광동체",
          specEng: "Wide Body Aircraft",
        },
      ],
    },
  ],
};

console.log(code);
